### ISSUE TITLE
Two tests fail due to floating point errors

### ISSUE THREAD

**Issue by kasbah** [mcous/gerber-plotter#6]
```
 123 passing (158ms)
  2 failing

  1) gerber plotter handling operation commands interpolating to create strokes arc strokes should determine the center and radius in single quadrant mode:

      AssertionError: expected [ Array(4) ] to deeply equal [ Array(4) ]
      + expected - actual

           "radius": 1.8027756377319946
           "start": [
             0
             0
      -      2.1587989303424644
      +      2.158798930342464
           ]
      -    "sweep": 1.1760052070951352
      +    "sweep": 1.1760052070951348
           "type": "arc"
         }
         {
           "center": [
           "radius": 1.8027756377319946
           "start": [
             2
             0
      -      4.124386376837122
      +      4.124386376837123
           ]
      -    "sweep": 1.1760052070951352
      +    "sweep": 1.1760052070951348
           "type": "arc"
         }
         {
           "center": [
      
      at Context.<anonymous> (test/gerber-plotter_test.js:1144:41)

  2) gerber plotter handling operation commands interpolating to create strokes arc strokes should use the actual offsets to get the center in multi-quadrant mode:

      AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
      + expected - actual

           "radius": 1.8027756377319946
           "start": [
             0
             0
      -      2.1587989303424644
      +      2.158798930342464
           ]
      -    "sweep": 1.1760052070951352
      +    "sweep": 1.1760052070951348
           "type": "arc"
         }
         {
           "center": [
           "radius": 1.8027756377319946
           "start": [
             2
             0
      -      4.124386376837122
      +      4.124386376837123
           ]
      -    "sweep": 1.1760052070951352
      +    "sweep": 1.1760052070951348
           "type": "arc"
         }
       ]
      
      at Context.<anonymous> (test/gerber-plotter_test.js:1192:41)
```

**Comment by mcous** [comment]
Dunno how easy this would be to cherry pick, but: https://github.com/tracespace/gerber-to-svg/commit/ca3b25447543178af53033ee007a06e9710a9024

**Comment by kasbah** [comment]
Do I need to cherry pick this fix if you are going to move everything into a monorepo anyway?

**Comment by mcous** [comment]
Believe it or not I have no timeline on that change and given my regular workload I think you'd be waiting a long time for me. What's pushed up to the `gerber-to-svg@next` branch isn't even my latest attempt at the monorepo...
